// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlmjialgwohlihomedjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsbWppYWxnd29obGlob21lZGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Nzc4NzksImV4cCI6MjA2NTE1Mzg3OX0.cS-0IyiAGSgYs4HZZUzSMFGSwKEkzeYubKbE2nssT6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);